version: "3"

services:
  cafecoder_docker:
    build: .
    image: cafecoder_docker:2407
    privileged: true
    env_file: .env
    volumes:
      - type: bind
        source: ./service-account-cafecoder.json
        target: /service-account.json
